// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ✅ IMPORTANT: set this to your Realtime Database URL from Firebase Console
  // Example formats:
  // https://mw-chat-prod-default-rtdb.firebaseio.com
  // https://mw-chat-prod-default-rtdb.<region>.firebasedatabase.app
  static const String _databaseUrl =
      'https://mw-chat-prod-default-rtdb.firebaseio.com';

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTS4pouaoBIH2QF-iq-Flce9qWayDZGxc',
    appId: '1:1007212667628:web:ada75a68a6f79d9e2b7bc9',
    messagingSenderId: '1007212667628',
    projectId: 'mw-chat-prod',
    authDomain: 'mw-chat-prod.firebaseapp.com',
    storageBucket: 'mw-chat-prod.firebasestorage.app',
    measurementId: 'G-PRGEPSB3D2',
    // ✅ ADD
    databaseURL: _databaseUrl,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYaMiSMOsSMrnKfSyWJZbmomeF3NY5n1w',
    appId: '1:1007212667628:ios:b4bf760ea9e44cb52b7bc9',
    messagingSenderId: '1007212667628',
    projectId: 'mw-chat-prod',
    storageBucket: 'mw-chat-prod.firebasestorage.app',
    iosBundleId: 'com.mwchat.app',
    // ✅ ADD
    databaseURL: _databaseUrl,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTGTGnZC-wx7tYNMCjMYBZcPlesAUJ1qk',
    appId: '1:1007212667628:android:564158376711dbeb2b7bc9',
    messagingSenderId: '1007212667628',
    projectId: 'mw-chat-prod',
    storageBucket: 'mw-chat-prod.firebasestorage.app',
    // ✅ ADD
    databaseURL: _databaseUrl,
  );
}
