// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYXZXQ8kFkynV__pfbv0V5NiZLsodMSrQ',
    appId: '1:131927411918:web:5c2bb5a184d2eb91a8949f',
    messagingSenderId: '131927411918',
    projectId: 'mw-app-821f8',
    authDomain: 'mw-app-821f8.firebaseapp.com',
    storageBucket: 'mw-app-821f8.firebasestorage.app',
    measurementId: 'G-QEJMCH4N0E',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC5x2PXdZ3bXZNn5usXnrnif5NqQ5HJzM',
    appId: '1:131927411918:ios:0739f38df6c13019a8949f',
    messagingSenderId: '131927411918',
    projectId: 'mw-app-821f8',
    storageBucket: 'mw-app-821f8.firebasestorage.app',
    iosBundleId: 'com.example.mw',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCIqNCaORbXa-oVpM5uH7xli9aLcQi13Q',
    appId: '1:131927411918:android:4c2f8c048a11dc37a8949f',
    messagingSenderId: '131927411918',
    projectId: 'mw-app-821f8',
    storageBucket: 'mw-app-821f8.firebasestorage.app',
  );

}