// MW Chat – Modern private messaging app
// Copyright © 2025 Mousa Abu Hilal. All rights reserved.
// lib/main.dart

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:mw/screens/home/home_screen.dart';
import 'package:provider/provider.dart';

import 'firebase_options.dart';
import 'screens/auth/auth_screen.dart';
import 'screens/profile/profile_screen.dart';
import 'theme/app_theme.dart';
import 'utils/presence_service.dart';
import 'l10n/app_localizations.dart';
import 'utils/locale_provider.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Start presence tracking once Firebase is ready.
  PresenceService.instance.init();

  runApp(
    ChangeNotifierProvider(
      create: (_) => LocaleProvider(),
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    final localeProvider = context.watch<LocaleProvider>();

    return MaterialApp(
      title: 'MW Chat',
      theme: buildAppTheme(),
      debugShowCheckedModeBanner: false,

      // Current app locale (can be changed at runtime)
      locale: localeProvider.locale,

      // Localization setup (generated by flutter gen-l10n)
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales,

      // Decide which screen to show based on auth + profile state
      home: const AuthGate(),
    );
  }
}

/// Redirects user depending on login state + profile completeness + activation.
class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  bool _isProfileComplete(Map<String, dynamic>? data) {
    if (data == null) return false;

    final firstName = (data['firstName'] ?? '').toString().trim();
    final lastName = (data['lastName'] ?? '').toString().trim();
    final gender = (data['gender'] ?? '').toString();
    final birthday = data['birthday'];

    final hasFirstName = firstName.isNotEmpty;
    final hasLastName = lastName.isNotEmpty;
    final hasGender = gender == 'male' || gender == 'female';
    final hasBirthday = birthday != null; // Timestamp or string is fine

    return hasFirstName && hasLastName && hasGender && hasBirthday;
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;

    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, authSnap) {
        if (authSnap.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }

        final user = authSnap.data;
        if (user == null) {
          // Not logged in → go to auth screen
          return const AuthScreen();
        }

        // Logged in → watch user doc (profile + isActive)
        return StreamBuilder<DocumentSnapshot<Map<String, dynamic>>>(
          stream: FirebaseFirestore.instance
              .collection('users')
              .doc(user.uid)
              .snapshots(),
          builder: (context, userSnap) {
            if (userSnap.connectionState == ConnectionState.waiting) {
              return const Scaffold(
                body: Center(child: CircularProgressIndicator()),
              );
            }

            if (!userSnap.hasData || !userSnap.data!.exists) {
              // User doc not yet created (small window after registration)
              return Scaffold(
                body: Center(
                  child: Text(l10n.settingUpProfile),
                ),
              );
            }

            final data = userSnap.data!.data() ?? {};

            // 1) If profile is missing required fields → force ProfileScreen
            if (!_isProfileComplete(data)) {
              // User can fill first/last name, birthday, gender here
              return const ProfileScreen();
            }

            // 2) Profile is complete; check activation
            final isActive = data['isActive'] == true;
            if (!isActive) {
              // Account created but not activated yet
              return Scaffold(
                body: Center(
                  child: Padding(
                    padding: const EdgeInsets.all(24.0),
                    child: Column(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Text(
                          l10n.accountNotActive,
                          style: const TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.bold,
                          ),
                          textAlign: TextAlign.center,
                        ),
                        const SizedBox(height: 12),
                        Text(
                          l10n.waitForActivation,
                          textAlign: TextAlign.center,
                        ),
                        const SizedBox(height: 24),
                        ElevatedButton.icon(
                          onPressed: () async {
                            await FirebaseAuth.instance.signOut();
                          },
                          icon: const Icon(Icons.logout),
                          label: Text(l10n.logout),
                        ),
                      ],
                    ),
                  ),
                ),
              );
            }
            // 3) Active + profile complete → go to main user list
            return const HomeScreen();

          },
        );
      },
    );
  }
}
